<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260630201842 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT NOT NULL, icon_url VARCHAR(255) DEFAULT NULL, threshold INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FEF0481D5E237E06 ON badge (name)');
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9474526CF675F31B ON comment (author_id)');
        $this->addSql('CREATE INDEX IDX_9474526CE48FD905 ON comment (game_id)');
        $this->addSql('CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, api_id INT NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, home_score INT DEFAULT NULL, away_score INT DEFAULT NULL, home_team_id INT NOT NULL, away_team_id INT NOT NULL, season_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_232B318C54963938 ON game (api_id)');
        $this->addSql('CREATE INDEX IDX_232B318C9C4C13F6 ON game (home_team_id)');
        $this->addSql('CREATE INDEX IDX_232B318C45185D02 ON game (away_team_id)');
        $this->addSql('CREATE INDEX IDX_232B318C4EC001D1 ON game (season_id)');
        $this->addSql('CREATE INDEX idx_game_starts_at ON game (starts_at)');
        $this->addSql('CREATE TABLE league (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, invite_code VARCHAR(16) NOT NULL, is_private BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3EB4C3187E3C61F9 ON league (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_league_invite_code ON league (invite_code)');
        $this->addSql('CREATE TABLE league_membership (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, points INT NOT NULL, role VARCHAR(20) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, league_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E7C6620FA76ED395 ON league_membership (user_id)');
        $this->addSql('CREATE INDEX IDX_E7C6620F58AFC4DE ON league_membership (league_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_membership_user_league ON league_membership (user_id, league_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recipient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAE92F8F78 ON notification (recipient_id)');
        $this->addSql('CREATE INDEX idx_notification_recipient_read ON notification (recipient_id, is_read)');
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, api_id INT NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, position VARCHAR(50) DEFAULT NULL, team_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_98197A6554963938 ON player (api_id)');
        $this->addSql('CREATE INDEX IDX_98197A65296CD8AE ON player (team_id)');
        $this->addSql('CREATE TABLE prediction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, points_awarded INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, game_id INT NOT NULL, type VARCHAR(30) NOT NULL, predicted_winner_id INT DEFAULT NULL, predicted_home_score INT DEFAULT NULL, predicted_away_score INT DEFAULT NULL, stat_type VARCHAR(20) DEFAULT NULL, predicted_value DOUBLE PRECISION DEFAULT NULL, comparison VARCHAR(10) DEFAULT NULL, player_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_36396FC8A76ED395 ON prediction (user_id)');
        $this->addSql('CREATE INDEX IDX_36396FC8E48FD905 ON prediction (game_id)');
        $this->addSql('CREATE INDEX IDX_36396FC819EAE00D ON prediction (predicted_winner_id)');
        $this->addSql('CREATE INDEX IDX_36396FC899E6F5DF ON prediction (player_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_prediction_user_game_type ON prediction (user_id, game_id, type)');
        $this->addSql('CREATE TABLE season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, label VARCHAR(50) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, api_id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(10) NOT NULL, city VARCHAR(100) NOT NULL, conference VARCHAR(50) DEFAULT NULL, division VARCHAR(50) DEFAULT NULL, logo_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C4E0A61F54963938 ON team (api_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, username VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_username ON "user" (username)');
        $this->addSql('CREATE TABLE user_favorite_team (user_id INT NOT NULL, team_id INT NOT NULL, PRIMARY KEY (user_id, team_id))');
        $this->addSql('CREATE INDEX IDX_C4681270A76ED395 ON user_favorite_team (user_id)');
        $this->addSql('CREATE INDEX IDX_C4681270296CD8AE ON user_favorite_team (team_id)');
        $this->addSql('CREATE TABLE user_badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, earned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, badge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1C32B345A76ED395 ON user_badge (user_id)');
        $this->addSql('CREATE INDEX IDX_1C32B345F7A2C2FC ON user_badge (badge_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_badge ON user_badge (user_id, badge_id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CE48FD905 FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C9C4C13F6 FOREIGN KEY (home_team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C45185D02 FOREIGN KEY (away_team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE league ADD CONSTRAINT FK_3EB4C3187E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE league_membership ADD CONSTRAINT FK_E7C6620FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE league_membership ADD CONSTRAINT FK_E7C6620F58AFC4DE FOREIGN KEY (league_id) REFERENCES league (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prediction ADD CONSTRAINT FK_36396FC8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prediction ADD CONSTRAINT FK_36396FC8E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prediction ADD CONSTRAINT FK_36396FC819EAE00D FOREIGN KEY (predicted_winner_id) REFERENCES team (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prediction ADD CONSTRAINT FK_36396FC899E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_favorite_team ADD CONSTRAINT FK_C4681270A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_favorite_team ADD CONSTRAINT FK_C4681270296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526CF675F31B');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526CE48FD905');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C9C4C13F6');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C45185D02');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C4EC001D1');
        $this->addSql('ALTER TABLE league DROP CONSTRAINT FK_3EB4C3187E3C61F9');
        $this->addSql('ALTER TABLE league_membership DROP CONSTRAINT FK_E7C6620FA76ED395');
        $this->addSql('ALTER TABLE league_membership DROP CONSTRAINT FK_E7C6620F58AFC4DE');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAE92F8F78');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A65296CD8AE');
        $this->addSql('ALTER TABLE prediction DROP CONSTRAINT FK_36396FC8A76ED395');
        $this->addSql('ALTER TABLE prediction DROP CONSTRAINT FK_36396FC8E48FD905');
        $this->addSql('ALTER TABLE prediction DROP CONSTRAINT FK_36396FC819EAE00D');
        $this->addSql('ALTER TABLE prediction DROP CONSTRAINT FK_36396FC899E6F5DF');
        $this->addSql('ALTER TABLE user_favorite_team DROP CONSTRAINT FK_C4681270A76ED395');
        $this->addSql('ALTER TABLE user_favorite_team DROP CONSTRAINT FK_C4681270296CD8AE');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B345A76ED395');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B345F7A2C2FC');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE league');
        $this->addSql('DROP TABLE league_membership');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE prediction');
        $this->addSql('DROP TABLE season');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_favorite_team');
        $this->addSql('DROP TABLE user_badge');
    }
}